# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Crev < Formula
  desc "CLI tool for AI code reviews"
  homepage "https://github.com/vossenwout/crev"
  version "0.0.6"

  on_macos do
    on_intel do
      url "https://github.com/vossenwout/crev/releases/download/v0.0.6/crev_Darwin_x86_64.tar.gz"
      sha256 "2061e509ed32b0b479d46979feed77365b1b234e9030c799597d135c386b48da"

      def install
        bin.install "crev"
      end
    end
    on_arm do
      url "https://github.com/vossenwout/crev/releases/download/v0.0.6/crev_Darwin_arm64.tar.gz"
      sha256 "200b908d581123f8ff16de8b2c1e8d8aa9c92d01fbe10b8516d5137914eceed4"

      def install
        bin.install "crev"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vossenwout/crev/releases/download/v0.0.6/crev_Linux_x86_64.tar.gz"
        sha256 "87ae46dbaa91c34abacc333247cee36d2f38d8ff8e9e5661431929d61149f65f"

        def install
          bin.install "crev"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vossenwout/crev/releases/download/v0.0.6/crev_Linux_arm64.tar.gz"
        sha256 "b38d04efe2b311a3aa7c66e3421478c428888cef973e57be8cac6f58da6a2093"

        def install
          bin.install "crev"
        end
      end
    end
  end
end
